// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANmW5khaiDcXkQNAaK06uHvDVr84ept5U',
    appId: '1:694480458294:web:062528d64783291938be97',
    messagingSenderId: '694480458294',
    projectId: 'fitgeek-63be2',
    authDomain: 'fitgeek-63be2.firebaseapp.com',
    storageBucket: 'fitgeek-63be2.appspot.com',
    measurementId: 'G-29SFRP21Y5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOHTfM3oIWIIbjCKi_4BciY1aZjH48s34',
    appId: '1:694480458294:android:0b8e3071030ffa9138be97',
    messagingSenderId: '694480458294',
    projectId: 'fitgeek-63be2',
    storageBucket: 'fitgeek-63be2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCt3HYMW819g0h5eXeMdtumz8nkhGGeVEk',
    appId: '1:694480458294:ios:64d7a6f3f55b570e38be97',
    messagingSenderId: '694480458294',
    projectId: 'fitgeek-63be2',
    storageBucket: 'fitgeek-63be2.appspot.com',
    iosBundleId: 'com.example.fitgeek',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCt3HYMW819g0h5eXeMdtumz8nkhGGeVEk',
    appId: '1:694480458294:ios:9b61934df93651b238be97',
    messagingSenderId: '694480458294',
    projectId: 'fitgeek-63be2',
    storageBucket: 'fitgeek-63be2.appspot.com',
    iosBundleId: 'com.example.fitgeek.RunnerTests',
  );
}
